### ISSUE TITLE
Missing data in ME1 data format

### ISSUE THREAD

**Issue by KarlitosVII** [electronicarts/MELE_ModdingSupport#1]
Hello,
First of all, as developer of [Trilogy Save Editor](https://github.com/KarlitosVII/trilogy-save-editor) I want to thank you very much for this repo. It will help me a lot in the future.
However, while digging in the code I noticed that there is a big chunk of data missing in `ME1_Savegame.h`.
I added some of the missing data in the following commit based on my research of the last few weeks but there is still a lot of data that I don't know about.

https://github.com/KarlitosVII/MELE_ModdingSupport/commit/7d92b8be4b0c3b2e9526dfa2886139240f47b870

It would be nice if you could fix it. :)
Thank you.

**Comment by BlanckCarbon** [comment]
That is very possible! Thank you for the commit, I'll review it when I get a bit of time! 😀

**Comment by BlanckCarbon** [comment]
I've updated the descriptor and filled in a few of the blanks - thank you for pointing it out! If we're still missing anything, please feel free to send another issue our way and we'll fix it up! 😀
