### ISSUE TITLE
Missing boolean data in ME1 plot db

### ISSUE THREAD

**Issue by KarlitosVII** [electronicarts/MELE_ModdingSupport#2]
Hello, it's me again.
Inserts for the `t_PlotBoolExportIDs` table are missing in `bw_me1_script.sql`

Cheers. :)

**Comment by Exkywor** [comment]
Yup, I noticed this too
(everything else is like heaven on earth though, thanks a lot for this)

**Comment by BlanckCarbon** [comment]
Thanks, looking into it!

**Comment by BlanckCarbon** [comment]
Should be resolved now!
